import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";

export const Route = createFileRoute("/auth")({ head:()=>({meta:[{title:"Portfolio Editor Sign In — Catherine Andrew"},{name:"description",content:"Secure owner access to Catherine Andrew's portfolio editor."},{property:"og:title",content:"Portfolio Editor Sign In — Catherine Andrew"},{property:"og:description",content:"Secure owner access to the portfolio editor."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}), component: AuthPage });
function AuthPage(){const navigate=useNavigate();const[error,setError]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user)navigate({to:"/editor",replace:true});});},[navigate]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const{error}=await supabase.auth.signInWithPassword({email:String(f.get("email")),password:String(f.get("password"))});setBusy(false);if(error){setError("That sign-in did not work. Check your details and try again.");return;}navigate({to:"/editor"});}async function reset(){setError("");const email=(document.querySelector<HTMLInputElement>('input[name="email"]')?.value??"").trim();if(!email){setError("Enter your editor email address first.");return;}const{error:resetError}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});if(resetError)setError("A password link could not be sent. Please try again.");else setNotice("Check your email for a secure password link.");}async function google(){const r=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin+"/auth"});if(r.error)setError("Google sign-in could not be started.");else if(!r.redirected)navigate({to:"/editor"});}return <main className="grid min-h-screen place-items-center px-5 py-12"><div className="w-full max-w-md"><a href="/" className="mb-10 inline-flex items-center gap-2 text-sm"><ArrowLeft className="h-4 w-4"/>Back to portfolio</a><div className="border bg-card p-7 sm:p-10"><LockKeyhole className="text-sage"/><h1 className="mt-6 font-display text-4xl font-semibold">Portfolio Editor</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Private access for Catherine to update content, uploads, and messages.</p><form onSubmit={submit} className="mt-8 space-y-4"><Input name="email" type="email" required placeholder="Email address"/><Input name="password" type="password" required minLength={8} placeholder="Password"/><Button className="w-full" disabled={busy}>{busy?"Signing in…":"Sign in"}</Button></form><Button variant="link" className="mt-2 w-full" onClick={reset}>Set or reset password</Button><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>or<span className="h-px flex-1 bg-border"/></div><Button variant="outline" className="w-full" onClick={google}>Continue with Google</Button>{notice&&<p className="mt-4 text-sm text-sage" role="status">{notice}</p>}{error&&<p className="mt-4 text-sm text-destructive" role="alert">{error}</p>}</div></div></main>}
