import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { ArrowDown, ArrowUpRight, BriefcaseBusiness, Check, CloudUpload, Mail, MapPin, Menu, Phone, Send, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { assetUrl, getPortfolio } from "@/lib/portfolio-data";
import { defaultContent, strengths, type PortfolioContent } from "@/lib/portfolio";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Catherine Andrew — Executive Virtual Assistant" },
    { name: "description", content: "Catherine Andrew provides reliable executive virtual assistance and administrative support from Lagos, Nigeria." },
    { property: "og:title", content: "Catherine Andrew — Executive Virtual Assistant" },
    { property: "og:description", content: "Reliable, organized remote administrative support for busy professionals and businesses." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: Portfolio,
});

const nav: Array<[string, string]> = [["Home","home"],["About","about"],["Services","services"],["Tools","tools"],["My Work","work"],["Certifications","certifications"],["Process","process"],["Resume","resume"],["Contact","contact"]];
const why = ["Reliable administrative support","Strong organizational skills","Attention to detail","Professional communication","Ability to work independently","Comfortable with remote collaboration","Willingness to learn and adapt","Focus on completing tasks accurately and efficiently"];
const process = [["01","Understand","I understand the task, priorities, expectations, and desired outcome."],["02","Organize","I organize information, tasks, schedules, and priorities into a clear workflow."],["03","Execute","I complete assigned tasks carefully, efficiently, and professionally."],["04","Communicate","I provide clear updates and ensure tasks are completed according to expectations."]];

function Media({ src, label, uploadType = "photo", className = "aspect-[4/5]" }: { src: string | undefined; label: string; uploadType?: "photo" | "file"; className?: string }) {
  return <div className={`relative overflow-hidden border border-border bg-secondary ${className}`}>{src ? <img src={src} alt={label} className="h-full w-full object-cover" /> : <div className="upload-grid flex h-full min-h-52 flex-col items-center justify-center gap-4 p-6 text-center text-muted-foreground"><CloudUpload className="h-7 w-7"/><span className="text-xs font-semibold uppercase tracking-[.16em]">{label}</span><Button size="sm" asChild><a href="/editor">{uploadType==="photo"?"Upload Photo":"Upload File"}</a></Button></div>}</div>;
}
function SectionTitle({ number, title, intro }: { number: string; title: string; intro?: string }) { return <div className="mb-10 grid gap-3 md:grid-cols-[180px_1fr]"><p className="text-xs font-bold uppercase tracking-[.18em] text-taupe">{number}</p><div><h2 className="font-display text-5xl font-semibold leading-none md:text-7xl">{title}</h2>{intro && <p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">{intro}</p>}</div></div>; }

function Portfolio() {
  const [content, setContent] = useState<PortfolioContent>(defaultContent); const [urls, setUrls] = useState<Record<string,string>>({}); const [open,setOpen]=useState(false); const [sent,setSent]=useState(false); const [busy,setBusy]=useState(false);
  useEffect(() => { getPortfolio().then(async c => { setContent(c); const entries = await Promise.all(Object.entries({heroPhoto:c.heroPhoto,aboutPhoto:c.aboutPhoto,resume:c.resume,...c.work,...Object.fromEntries(c.certificates.map((x,i)=>[`certificate-${i}`,x.file]))}).map(async ([k,v])=>[k,await assetUrl(v)])); setUrls(Object.fromEntries(entries)); }); }, []);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); const f=new FormData(e.currentTarget); const payload={name:String(f.get("name")??"").trim(),email:String(f.get("email")??"").trim(),message:String(f.get("message")??"").trim()}; if(!payload.name||!/^\S+@\S+\.\S+$/.test(payload.email)||!payload.message){setBusy(false);return;} const {error}=await supabase.from("contact_messages").insert(payload); setBusy(false); if(!error){setSent(true);e.currentTarget.reset();} }
  const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setOpen(false)};
  return <div className="overflow-hidden">
    <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto grid h-16 max-w-7xl grid-cols-[minmax(0,1fr)_auto] items-center px-5 lg:px-8"><button onClick={()=>go("home")} className="min-w-0 text-left font-display text-xl font-bold">CA<span className="text-sage">.</span></button><nav className="hidden items-center gap-5 lg:flex">{nav.map(([l,id])=><button key={id} onClick={()=>go(id)} className="text-[11px] font-bold uppercase tracking-[.12em] text-muted-foreground transition hover:text-foreground">{l}</button>)}</nav><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(!open)} aria-label="Open menu">{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="grid border-t bg-background px-5 py-4 lg:hidden">{nav.map(([l,id])=><button key={id} onClick={()=>go(id)} className="border-b py-3 text-left text-sm">{l}</button>)}</nav>}</header>

    <main>
      <section id="home" className="mx-auto grid min-h-[calc(100svh-4rem)] max-w-7xl items-center gap-10 px-5 py-12 lg:grid-cols-[1.08fr_.92fr] lg:px-8 lg:py-16">
        <div className="reveal"><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-taupe">Based in {content.location}</p><h1 className="font-display text-6xl font-semibold leading-[.9] md:text-8xl xl:text-9xl">{content.name}</h1><p className="mt-7 text-sm font-bold uppercase tracking-[.12em] text-sage">{content.title}</p><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">{content.hero}</p><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" onClick={()=>go("work")}>View My Work <ArrowDown/></Button><Button variant="outline" size="lg" onClick={()=>go("contact")}>Get In Touch <ArrowUpRight/></Button></div></div>
        <div className="relative mx-auto w-full max-w-md lg:mr-0"><div className="absolute -left-4 top-8 hidden h-full w-full border border-taupe/40 md:block"/><Media src={urls["heroPhoto"]} label="Add Professional Photo" className="aspect-[4/5]"/><p className="mt-4 text-right text-[10px] font-bold uppercase tracking-[.18em] text-muted-foreground">Executive support · Thoughtfully organized</p></div>
      </section>

      <section id="about" className="section-rule bg-card"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionTitle number="01 / About" title="Professional support, personal care."/><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><Media src={urls["aboutPhoto"]} label="Add About Me Photo" className="aspect-[4/5]"/><div><h3 className="font-display text-4xl font-semibold">About Me</h3><div className="mt-6 space-y-5 text-base leading-8 text-muted-foreground">{content.about.map((p,i)=><p key={i}>{p}</p>)}</div><h3 className="mt-12 font-display text-3xl font-semibold">What I Bring</h3><div className="mt-5 grid grid-cols-2 gap-px bg-border sm:grid-cols-3">{strengths.map((x,i)=><div key={x} className="bg-card p-5"><span className="text-xs text-taupe">0{i+1}</span><p className="mt-6 text-sm font-semibold">{x}</p></div>)}</div></div></div></div></section>

      <section id="services"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionTitle number="02 / Services" title="The support behind your best work."/><div className="grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{content.services.map(([t="",d=""],i)=><article className="group bg-background p-7 transition hover:bg-secondary" key={`${t}-${i}`}><span className="text-xs text-taupe">0{i+1}</span><BriefcaseBusiness className="mt-10 text-sage"/><h3 className="mt-5 font-display text-2xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{d}</p></article>)}</div></div></section>

      <section id="tools" className="section-rule bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><SectionTitle number="03 / Toolkit" title="Tools I work with." intro="Digital platforms I am familiar with and have practiced using to support organized, efficient remote work."/><div className="flex flex-wrap gap-2">{content.tools.map((t,i)=><div key={`${t}-${i}`} className="border border-primary-foreground/20 px-5 py-4 text-sm"><span className="mr-3 text-primary-foreground/45">{String(i+1).padStart(2,"0")}</span>{t}</div>)}</div></div></section>

      <section id="work"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionTitle number="04 / Portfolio" title="My Work" intro="Selected spaces for real work samples. Screenshots will be added here as the portfolio grows."/><div className="grid gap-7 md:grid-cols-2">{content.workItems.map((item,i)=><article key={`${item.title}-${i}`} className="border border-border bg-card"><Media src={urls[`work-${i}`]} label="Add Work Screenshot" className="aspect-video"/><div className="p-6"><h3 className="font-display text-2xl font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.description}</p><p className="mt-5 border-t pt-4 text-xs uppercase tracking-[.12em] text-taupe">Tools used · {item.tools}</p></div></article>)}</div></div></section>

      <section id="certifications" className="section-rule bg-card"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionTitle number="05 / Development" title="Certifications" intro="Professional development and training that support my work as an Executive Virtual Assistant."/><div className="grid gap-6 md:grid-cols-3">{content.certificates.map((c,i)=><article key={i} className="border bg-background"><Media src={urls[`certificate-${i}`]} label={i===0?"Add Certificate":"Add Future Certificate"} className="aspect-[4/3]"/><div className="p-5"><h3 className="font-display text-xl font-semibold">{c.title}</h3><p className="mt-1 text-sm text-muted-foreground">{c.issuer||"Issuing organization"}{c.date&&` · ${c.date}`}</p>{urls[`certificate-${i}`]&&<a href={urls[`certificate-${i}`]} target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs font-bold uppercase tracking-[.12em] underline">View Certificate</a>}</div></article>)}</div></div></section>

      <section id="process"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionTitle number="06 / Process" title="How I Work"/><div className="grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-4">{process.map(([n,t,d])=><article key={n} className="bg-background p-7"><span className="font-display text-4xl text-taupe">{n}</span><h3 className="mt-10 text-lg font-bold">{t}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{d}</p></article>)}</div><div className="mt-20 grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><h2 className="font-display text-5xl font-semibold">Why work with me?</h2><div className="grid gap-0 sm:grid-cols-2">{why.map(x=><div key={x} className="flex gap-3 border-b py-4 text-sm"><Check className="h-4 w-4 shrink-0 text-sage"/>{x}</div>)}</div></div></div></section>

      <section id="resume" className="section-rule bg-secondary"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-20 lg:grid-cols-[1fr_auto] lg:items-end lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-taupe">07 / Resume</p><h2 className="mt-4 font-display text-6xl font-semibold">The details,<br/>all in one place.</h2><p className="mt-5 max-w-xl leading-7 text-muted-foreground">Interested in learning more about my professional background and skills? You can view or download my resume below.</p></div>{urls["resume"]?<Button size="lg" asChild><a href={urls["resume"]} download>Download My Resume <ArrowDown/></a></Button>:<div className="border border-dashed border-taupe px-8 py-6 text-center"><CloudUpload className="mx-auto text-taupe"/><p className="mt-3 text-xs font-bold uppercase tracking-[.14em]">Resume upload ready</p><Button className="mt-4" size="sm" asChild><a href="/editor">Upload File</a></Button></div>}</div></section>

      <section id="contact" className="bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionTitle number="08 / Contact" title="Let’s Work Together" intro="Have an administrative task, project, or remote support opportunity? I’d love to hear from you."/><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-7 text-sm"><Contact icon={<Mail/>} label="Email" value={content.email||"[Add Your Email]"}/><Contact icon={<Phone/>} label="Phone" value={content.phone||"[Add Your Phone Number]"}/><Contact icon={<Phone/>} label="WhatsApp" value={content.whatsapp||"[Add Your WhatsApp Number]"} href={content.whatsapp?`https://wa.me/${content.whatsapp.replace(/\D/g,"")}`:undefined}/><Contact icon={<ArrowUpRight/>} label="LinkedIn" value={content.linkedin||"[Add Your LinkedIn URL]"} href={content.linkedin||undefined}/><Contact icon={<MapPin/>} label="Location" value={content.location}/><div className="flex flex-wrap gap-2 pt-3"><Button variant="secondary" disabled={!content.email} asChild={!!content.email}>{content.email?<a href={`mailto:${content.email}`}>Email Me</a>:<span>Email Me</span>}</Button><Button variant="secondary" disabled={!content.whatsapp} asChild={!!content.whatsapp}>{content.whatsapp?<a href={`https://wa.me/${content.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">WhatsApp Me</a>:<span>WhatsApp Me</span>}</Button><Button variant="secondary" disabled={!content.linkedin} asChild={!!content.linkedin}>{content.linkedin?<a href={content.linkedin} target="_blank" rel="noreferrer">LinkedIn</a>:<span>LinkedIn</span>}</Button></div></div><form onSubmit={submit} className="space-y-5 border-t border-primary-foreground/25 pt-8"><label className="block text-xs font-bold uppercase tracking-[.14em]">Name<Input name="name" required maxLength={100} className="mt-2 h-12 border-primary-foreground/30 text-primary-foreground placeholder:text-primary-foreground/45" placeholder="Your name"/></label><label className="block text-xs font-bold uppercase tracking-[.14em]">Email<Input name="email" type="email" required maxLength={255} className="mt-2 h-12 border-primary-foreground/30 text-primary-foreground placeholder:text-primary-foreground/45" placeholder="you@example.com"/></label><label className="block text-xs font-bold uppercase tracking-[.14em]">Message<Textarea name="message" required maxLength={2000} className="mt-2 min-h-36 border-primary-foreground/30 text-primary-foreground placeholder:text-primary-foreground/45" placeholder="Tell me about the support you need"/></label><Button variant="secondary" size="lg" disabled={busy}>{busy?"Sending…":"Send Message"}<Send/></Button>{sent&&<p role="status" className="text-sm">Thank you — your message has been received.</p>}</form></div></div></section>
    </main><footer className="flex flex-col gap-3 border-t bg-primary px-5 py-7 text-xs text-primary-foreground/60 sm:flex-row sm:justify-between lg:px-8"><p>© 2026 {content.name}</p><a href="/auth" className="hover:text-primary-foreground">Portfolio editor</a></footer>
  </div>;
}
function Contact({icon,label,value,href}:{icon:ReactNode;label:string;value:string;href?:string}) { return <div className="grid grid-cols-[24px_80px_minmax(0,1fr)] items-start gap-3 border-b border-primary-foreground/15 pb-5"><span className="[&_svg]:h-4 [&_svg]:w-4">{icon}</span><span className="text-primary-foreground/55">{label}</span>{href?<a href={href} target="_blank" rel="noreferrer" className="break-words underline decoration-primary-foreground/40 underline-offset-4">{value}</a>:<span className="break-words">{value}</span>}</div>; }
